### ISSUE TITLE
[Enhancement]: Implement automatic intro/credit detection for newly added or modified episodes.

### ISSUE THREAD

**Issue by rlauuzo** [jumoog/intro-skipper#95] opened 2024-03-28 14:56 UTC
Hi there,
I'd like to request a new feature: automatic intro and credit detection for newly added or modified episodes. Similar to the way JellyScrub offers "create trickplays when videos are discovered," this would significantly improve user experience by automatically identifying intros for new content.
Thanks for considering this!

**Comment by jumoog** [comment] 2024-03-28 15:04
duplicate of #88

**Comment by rlauu** [comment] 2024-03-28 15:12
Hi, thanks for letting me know about issue #88. I believe this request is quite different.

My request, aims to implement automatic intro/credit detection for newly added episodes. This functionality would directly improve user experience for managing fresh content in the library.

Interestingly, there's even a reference to this feature as a TODO in the code itself 
https://github.com/jumoog/intro-skipper/blob/9e7d0a74f0cc11d996703d16d5352b89f9be5ae6/ConfusedPolarBear.Plugin.IntroSkipper/Entrypoint.cs#L51

**Comment by AbandonedCart** [comment] 2024-03-28 15:50
If there is already a TODO for it, is this meant to be a reminder?

**Comment by jumoog** [comment] 2024-03-30 13:01
It works great but it should be visible in dashboard

**Comment by AbandonedCart** [comment] 2024-03-30 13:22
Since the original change, something is eating all my RAM lol

**Comment by rlauu** [comment] 2024-03-30 13:29
Had the same RAM problem. But https://github.com/jumoog/intro-skipper/pull/99 fixed it for me.

**Comment by AbandonedCart** [comment] 2024-04-09 21:12
I think @rlauuzo got this one done and addressed bugs in the process

**Closed by AbandonedCart** 2024-04-09 21:12 UTC
