### ISSUE TITLE
[Bug]: "Next up" display overlaps "Next" button in jellyfin web

### ISSUE THREAD

**Issue by alvitali** [jumoog/intro-skipper#220] opened 2024-07-24 00:35 UTC
### Self service debugging

- [X] Jellyfin is updated and my permissions are correct (or I did not use Docker)

### Describe the bug

The div container with the ".upNextContainer .upNextClass" classes (displayed when playback reaches x percent from the end of the episode) is shown simultaneously with the button from the intro-skipper button with the "#skipIntro" id.

<img width="410" alt="Screenshot 2024-07-24 at 02 31 32 edited" src="https://github.com/user-attachments/assets/07093df9-69cc-4b26-9713-94bfd82d09d3"><br>

I could just hide the ".upNextClass" with CSS overrides I suppose, but it was great if the plugin were to hide it by default.

### Jellyfin install method

Docker

### Container image/tag or Jellyfin version

jellyfin/jellyfin:10.9.8, jellyfin-intro-skipper:0.2.0.12

### Operating System

Debian 12

### Support Bundle

```shell
* Jellyfin version: 10.9.8
* Plugin version: 0.2.0+a13733bdad67
* Queue contents: 10383 episodes, 774 seasons
* Warnings: `InvalidChromaprintFingerprint`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12 (Debian 12.2.0-14)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by jumoog** [comment] 2024-07-25 19:57
duplicate of #158

**Closed by jumoog** 2024-07-25 19:57 UTC
Labels: bug
