### ISSUE TITLE
[Bug]: Unable to add skip intro button to work on jellyfin 10.9.7  

### ISSUE THREAD

**Issue by LanaFox2022** [jumoog/intro-skipper#211] opened 2024-07-08 23:14 UTC
### Self service debugging

- [X] Jellyfin is updated and my permissions are correct (or I did not use Docker)

### Describe the bug

I for some reason Can not figure out why i cant get the skip intro button to display.
Do i need a custom web UI ?
I have the latest plugin version and jelly fin and the required ffmpeg verson.
any ideas what i did wrong ?

### Jellyfin install method

Windows Installer

### Container image/tag or Jellyfin version

jellyfin 10.9.7

### Operating System

Windows 11 Pro

### Support Bundle

```shell
Jellyfin version: 10.9.7
* Plugin version: 0.2.0+6f127ca7bf58
* Queue contents: 3409 episodes, 204 seasons
* Warnings: `UnableToAddSkipButton`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 13-win32 (GCC)
configuration: --prefix=/opt/ffmpeg --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --disable-w32threads --enable-pthreads --enable-shared --enable-lto --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libsvtav1 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by AbandonedCart** [comment] 2024-07-09 00:07
Have you checked #104 ? 99% of the time, that is the issue.

**Comment by jumoog** [comment] 2024-07-09 09:33
Find `index.html` in `C:\Program Files\Jellyfin\Server\jellyfin-web` and modify the permissions for your user to Full Control. Then restart Jellyfin.

**Comment by jumoog** [comment] 2024-07-09 09:35
duplicate of #210

**Closed by jumoog** 2024-07-09 09:35 UTC
Labels: bug
